### ISSUE TITLE
3 [Vault] create deposit_and_invest function

### ISSUE THREAD

**Issue by chopan123** [paltalabs/defindex#151]
- [x] Contract should have deposit() and invest()
- [x] Contract should have deposit_and_invest()
- [x] deposit_and_invest function should calculate the current ratio in whicvh every asset has in every strategy
- [x] should  construct Vec<Option<AssetInvestmentAllocation>> and call private function check_and_execute_investments

**Comment by joaquinsoza** [comment]
#236
