### ISSUE TITLE
2 [Vault] [BUG] Withdraw throwing invalidAction when running typescript tests

### ISSUE THREAD

**Issue by chopan123** [paltalabs/defindex#157]
Typescript test that fail is on branch typescriptTests https://github.com/paltalabs/defindex/tree/typescriptTests

**Comment by chopan123** [comment]
Steps to reproduce:
1. `bash run.sh --nb`
2. `cd apps/contracts`
3. `yarn`
4. `yarn test testnet`

**Comment by esteblock** [comment]
Fixed in https://github.com/paltalabs/defindex/commit/687a1e23232541537a898dd636d9f5d3d602c08f
Please test and close @chopan123
