### ISSUE TITLE
2 [Blend Strategy] Better blend strategy errors

### ISSUE THREAD

**Issue by joaquinsoza** [paltalabs/defindex#301]
In the blend strategy multiple errors are being returned as InvalidArgument from the lack of specific errors to return in the core strategy package

Maybe recognize the missing types of errors and expand this errors types in the core package or implement a errors.rs specific for the blend strategy and return them as panic

**Comment by chopan123** [comment]
Common to strategy errors should be on core strategy
Blend Specific strategy errors should be on `error.rs` in Blend strategy.
Some examples:
- [ ] Add specific Blend new error when amount < MIN_DUST
- [ ] When:
  ```    if underlying_amount <= 0 {
        panic_with_error!(e, StrategyError::InvalidArgument); //TODO: create a new error type for this
    }
```
- [ ] When:
```
    if b_tokens_amount <= 0 {
        panic_with_error!(e, StrategyError::InvalidArgument); //TODO: create a new error type for this
    }
```
- [ ] When internal swap fails on `apps/contracts/strategies/blend/src/blend_pool.rs`
