### ISSUE TITLE
5 [Vault] Add Roles and management

### ISSUE THREAD

**Issue by chopan123** [paltalabs/defindex#56]
hacer un `.rs` que tiene el management. 

Roles: Deployer, Fee Receiver, Manager and Emergency Manager

Functions:
- set roles
- Manager can change manager
- Fee Receiver can change Fee Receiver

References: Blend & Yearn & AQUA
https://github.com/AquaToken/soroban-amm/blob/master/access_control/src/access.rs
https://github.com/AquaToken/soroban-amm/blob/master/liquidity_pool/src/contract.rs

**Comment by joaquinsoza** [comment]
#63
