### ISSUE TITLE
3 [Vault & Factory] Add 2 fee receivers, Paltalabs and Fee Receiver

### ISSUE THREAD

**Issue by joaquinsoza** [paltalabs/defindex#68]
The vault should have 2 fee receivers, one for paltalabs which is set by the factory and can only be updated by the factory admin in the factory contract.

- [x] Add paltalabs fee receiver in initialize
- [x] Add Fee Receiver for paltalabs
- [x] Update factory to have admin and fee_receiver

**Comment by joaquinsoza** [comment]
https://github.com/paltalabs/defindex/pull/70

**Comment by esteblock** [comment]
Closing as merged
