### ISSUE TITLE
3 [Strategy] Add events & change base_strategy to test_strategy

### ISSUE THREAD

**Issue by joaquinsoza** [paltalabs/defindex#76]
We should add events at the interface level, change the interface package to strategy_base this way it will make more sense (naming wise) to have the events every strategy should publish

- [x] rename base_strategy to test_strategy
- [x] rename interface package to strategy_base
- [x] add events.rs to the base_strategy
- [x] update soroswap, xycloans and test_strategy to use the strategy_base so it compiles
- [x] add events to the test_strategy

**Comment by joaquinsoza** [comment]
#78

**Comment by esteblock** [comment]
Closing as merged
