### ISSUE TITLE
2 [Frontend] Fetch Strategies from github public/network.contracts.json

### ISSUE THREAD

**Issue by chopan123** [paltalabs/defindex#89]
- [x] a partir de esto modificar lista de adapters que uno pueda elegir
- [x] quitar el Custom

**Comment by MattPoblete** [comment]
Eliminar opcion de custom strategy

**Comment by MattPoblete** [comment]
I've just created getRemoteConfig.ts to fetch the addresses from remote and refactored useFactory to use this new helper!
